spring:
  application:
    name: auth-service
  redis:
    host: 192.168.47.84
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/heima?allowMultiQueries=true
    username: root
    password: 123456
server:
  port: 8087

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true

#这里是公钥和私钥的地方
ly:
  jwt:
    pubKeyPath: C:/Users/kafei/.ssh/rsa/id_rsa.pub # 公钥地址
    priKeyPath: C:/Users/kafei/.ssh/rsa/id_rsa # 私钥地址
    user:
      expire: 30 # 过期时间,单位分钟
      cookieName: LY_TOKEN # cookie名称
      cookieDomain: leyou.com # cookie的域
      minRefreshInterval:  15 #cookie的最小刷新间隔
    app:
      id: 10
      secret: auth-service # auth服务的密钥，默认也是服务名称
      expire: 1500  #服务的过期时间 分钟
      headerName: privilege_token   #token的请求头名称
  encoder:
      crypt:
        secret: ${random.uuid}
        strength: 10
mybatis:
  type-aliases-package:   com.leyou.auth.entity
  mapper-locations: mappers/*.xml
  configuration:
      map-underscore-to-camel-case: true
mapper:
  wrap-keyword: "`{0}`"

#加密


