server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.47.97
    username: leyou
    password: leyou
    virtual-host: /leyou
ly:
  sms:
    accessKeyID: LTAIZVxQu9ikvIBZ # 你自己的accessKeyId
    accessKeySecret: ojc0V8LdNjoS4QxytNPKNpiFilH7cD # 你自己的AccessKeySecret
    signName: XD商城 # 签名名称
    verifyCodeTemplate: SMS_168587436 # 模板名称
    domain: dysmsapi.aliyuncs.com # 域名
    action: SendSMS # API类型，发送短信
    version: 2017-05-25 # API版本，固定值
    regionID: cn-hangzhou # 区域id


