
server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/heima
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.47.84
  rabbitmq:
    host: 192.168.47.84
    username: leyou
    password: leyou
    virtual-host: /leyou
ly:
  encoder:
    crypt:
      secret: ${random.uuid} # 随机的密钥，使用uuid
      strength: 4 # 加密强度4~31，决定了密码和盐加密时的运算次数，超过10以后加密耗时会显著增加
  jwt:
    pubKeyPath: C:/Users/kafei/.ssh/rsa/id_rsa.pub # 公钥地址
    user:
      cookieName: LY_TOKEN # cookie名称
    app:
      id: 1 # 服务id
      secret: user-service # 服务密钥，默认是服务的名称
      headerName: privilege_token
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
mybatis:
  type-aliases-package: com.leyou.user.entity
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.leyou: debug
