server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/heima?useSSL=false
    username: root
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
      prefer-ip-address: true
      ip-address: 127.0.0.1
mybatis:
  type-aliases-package: com.leyou.entity
  configuration:
      map-underscore-to-camel-case: true        #什么意思
  mapper-locations: mapper/*.xml
mapper:
  wrap-keyword: "`{0}`"
logging:
  level:
    com.leyou: debug